language: java
jdk:
  - oraclejdk8
dist:
  trusty
cache:
  directories:
      - $HOME/.m2
notification:
  email:
    recipients:
      -  wcmeng@ctrip.com
    on_success: always
    on_failure: always

before_script:
  
before_install:

script:
    echo "skip test...."

after_success:
  - mvn -Dlog.console.close=true  clean generate-resources cobertura:cobertura coveralls:report

branches:
  only:
    - master
    - dev
    - coverity_scan
    
env:
  global:
   - secure: "BZ5aKdIPRoUyOnfAP8iwVYDG5rUhfhXfcZHhaPu0u04YDWtmcpsXtc3+ZJLkwQP+u2dSGaCbLFZXh87BoNYsd4pGvBSL1kXrsencUU8FJZUUHYQnmThVXzBlQidOU4cLvgVTii2cXsR3n6rs07b5KbWsGOrVjHFaReFRWv1X46Fnr8VgFrJQS8P1ZWGYj+2ZEZy586TVtLCeQs9MrVw/Oqh+zw00ehoi6LlPwbpFbzsh4KQiLm6yLuuxbgqKymCgzWYvrs168/2abRq9WptYOZrF4gyNtqeAJOv1+vlmhCzcpjJrsTzgSZAN5kvTiklXjyGAGAGXa3DKiXiCIsOuHmMZy1xY+6xII8V951wp/WmjGHRsTCtjuqhmBA+VntXnqVFfZBzHKrK55QFbrgfuaLY45lbhrqd5/XsvjTrdsILJK9Q/gtM6xNl4F6BbYWhHtyTHn9eHajxy5XwIB6UqZXMkeQHIsTlCM83OZrKEoXJR+QPHE9tnYT4b7bNyU+7PAgIkVb1MiScK0u5ZLwB8Rstf/QznQBA+K22x82rqzQgBSZbfW66RtMspvwyU+RL0brE9xI13fHv91yOi9piiC7Wb0GcSxO8nY/ktKeKAsNV6UJNcMU1H/gyiid5W2it5JcOI0eDDGvF75j6wm9WPuAGK0SkdVpDapZKhoA/lEyY="
   - "MAVEN_OPTS=-Xmx2g"

addons:
  coverity_scan:
    project:
      name: "ctripcorp/x-pipe"
      description: "Build submitted via Travis CI"
    notification_email:  wcmeng@ctrip.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
